Samfundet/Samfundet4

frontend/src/Pages/LoginPage/LoginPage.module.scss
=> Remove unnecessary background-color from LoginPage container

frontend/src/Components/AdminBox/AdminBox.stories.tsx
The AdminBox component uses `useNavigate()` cannot be done outside a Router instance
=> Fix AdminBox storybook

backend/root/management/commands/seed_scripts/__init__.py, backend/root/management/commands/seed_scripts/documents.py
Adds seed script for saksdokumenter
~~Based on branch from #257, merge this first to get rid of all the commits by mathias~~ Fixed and rebased.
Currently does not link to a document, could add this if needed just to see if download is working. 
Er altså bare `backend/root/management/commands/seed_scripts/documents.py` og `backend/root/management/commands/seed_scripts/__init__.py` som er changes her.
=> 391 seed for saksdokumenter

docs/README.md, docs/dev-tips.md
From me, to future webbers with ❤️
=> Add documentation for seeding (new dev tips markdown page)

frontend/.gitignore, frontend/src/Components/AccessDenied/AccessDenied.module.scss, frontend/src/Components/AccessDenied/AccessDenied.stories.tsx, frontend/src/Components/AccessDenied/AccessDenied.tsx
Identical to https://samfundet.no/403
=> Add AccessDenied component

frontend/src/AppRoutes.tsx, frontend/src/Pages/RouteOverviewPage/RouteOverviewPage.tsx, frontend/src/Pages/RouteOverviewPage/index.ts, frontend/src/Pages/index.ts, frontend/src/routes/frontend.ts, frontend/src/routes/index.ts
Vet ikke om den har så mye verdi.
Minimalistisk page som kan ta en iterasjon på design og funksjonalitet i senere steg.
=> Add page for route overview.

frontend/src/AppRoutes.tsx, frontend/src/Components/CrudButtons/CrudButtons.module.scss, frontend/src/Components/CrudButtons/CrudButtons.stories.tsx, frontend/src/Components/CrudButtons/CrudButtons.tsx, frontend/src/Components/CrudButtons/index.ts, frontend/src/Components/TabBar/TabBar.stories.tsx, frontend/src/Components/TabBar/TabBar.tsx, frontend/src/Pages/AdminPage/applets.ts, frontend/src/PagesAdmin/EventsAdminPage/EventsAdminPage.tsx, frontend/src/PagesAdmin/GangsAdminPage/GangsAdminPage.tsx, frontend/src/PagesAdmin/GangsFormAdminPage/GangsFormAdminPage.tsx, frontend/src/PagesAdmin/InformationAdminPage/InformationAdminPage.tsx, frontend/src/PagesAdmin/SaksdokumentAdminPage/SaksdokumentAdminPage.module.scss, frontend/src/PagesAdmin/SaksdokumentAdminPage/SaksdokumentAdminPage.tsx, frontend/src/PagesAdmin/SaksdokumentAdminPage/index.ts, frontend/src/PagesAdmin/SaksdokumentFormAdminPage/SaksdokumentFormAdminPage.tsx, frontend/src/i18n/constants.ts, frontend/src/i18n/translations.ts, frontend/src/routes/frontend.ts
Make forms handle edit/create new better, tabs for group types
Generic crud buttons for edit/delete in admin tables
Improve generic tabs
=> Fix and improve forms all around

backend/samfundet/models.py, backend/samfundet/serializers.py, backend/samfundet/views.py, frontend/src/Components/InputFile/InputFile.module.scss, frontend/src/Components/InputFile/InputFile.stories.tsx, frontend/src/Components/InputFile/InputFile.tsx, frontend/src/Components/InputFile/index.ts, frontend/src/Forms/SamfFormFieldTypes.tsx, frontend/src/PagesAdmin/ImageAdminPage/ImageAdminPage.tsx, frontend/src/PagesAdmin/ImageFormAdminPage/ImageFormAdminPage.tsx, frontend/src/api.ts, frontend/src/dto.ts, frontend/src/i18n/constants.ts, frontend/src/i18n/translations.ts
=> File input component (for images and PDFs)

frontend/src/Components/ImageQuery/ImageQuery.module.scss, frontend/src/Components/ImageQuery/ImageQuery.tsx, frontend/src/Forms/SamfForm.tsx, frontend/src/PagesAdmin/ImageAdminPage/ImageAdminPage.module.scss, frontend/src/PagesAdmin/ImageAdminPage/ImageAdminPage.tsx, frontend/src/PagesAdmin/ImageAdminPage/components/AdminImage/AdminImage.module.scss, frontend/src/PagesAdmin/ImageAdminPage/components/AdminImage/AdminImage.tsx
Improve styling, layout and behaviour
=> Cleanup image admin

frontend/src/utils.ts
Breaking change in dbt
Expected missing key to return undefined, throws instead and prevents page load.
=> Revert breaking change

frontend/src/Components/Link/Link.tsx, frontend/src/Components/Navbar/Navbar.module.scss, frontend/src/Components/Navbar/Navbar.tsx, frontend/src/Components/Navbar/components/HamburgerMenu/HamburgerMenu.module.scss, frontend/src/Components/Navbar/components/HamburgerMenu/HamburgerMenu.tsx
- Clicking name wouldn't close navbar popup in mobile
- Wrong color for hamburger on transparent background
=> Fix navbar close on mobile bug and hamburger colors

frontend/src/Components/Carousel/Carousel.tsx, frontend/src/Components/Dropdown/Dropdown.module.scss, frontend/src/Components/InputField/InputField.module.scss, frontend/src/Forms/SamfForm.tsx, frontend/src/PagesAdmin/EventCreatorAdminPage/EventCreatorAdminPage.module.scss, frontend/src/PagesAdmin/EventCreatorAdminPage/EventCreatorAdminPage.tsx, frontend/src/PagesAdmin/EventCreatorAdminPage/components/CustomTicketEditor.module.scss, frontend/src/PagesAdmin/EventCreatorAdminPage/components/CustomTicketEditor.tsx, frontend/src/types.ts
And fix it so it works again for adding new events
=> Cleanup event creator

frontend/src/Components/TabBar/TabBar.module.scss
=> Fix dark mode on TabBar.

frontend/src/Components/Footer/Footer.module.scss, frontend/src/Components/SamfundetLogoSpinner/SamfundetLogoSpinner.module.scss, frontend/src/global.scss
=> Add gradient.

frontend/src/Components/ImageCard/ImageCard.module.scss
**Before (2nd card hover)**
**After (2nd card hover)**
=> Tweak ImageCard box-shadow and border-radius

frontend/src/Components/Checkbox/Checkbox.tsx, frontend/src/Components/Checkbox/index.ts, frontend/src/Components/Dropdown/Dropdown.tsx, frontend/src/Components/Dropdown/index.ts, frontend/src/Components/ImagePicker/ImagePicker.tsx, frontend/src/Components/InputField/InputField.tsx, frontend/src/Components/InputField/index.ts, frontend/src/Components/InputFile/InputFile.tsx, frontend/src/Components/InputFile/index.ts, frontend/src/Components/TextAreaField/TextAreaField.tsx, frontend/src/Components/TextAreaField/index.ts, frontend/src/Components/index.ts, frontend/src/Forms/SamfForm.stories.tsx, frontend/src/Forms/SamfFormField.tsx, frontend/src/Forms/SamfFormFieldTypes.tsx
Added the ability to add props to the samf form field instead of being annoyed that you cant change specific aspects of a form such as aligment of checkboxes, or max rows of a text area field
=> add additonal props for samf form field

frontend/src/PagesAdmin/AdminLayout/AdminLayout.module.scss, frontend/src/PagesAdmin/AdminLayout/AdminLayout.tsx
=> add ability to close admin panel for desktop

backend/root/management/commands/seed_scripts/__init__.py, backend/root/management/commands/seed_scripts/users.py
=> [Development] Add seed for test users

backend/samfundet/models/recruitment.py
Getting these errors on master when building image:
```
samfundet.RecruitmentAdmission.recruiter_priority: (fields.E005) 'choices' must be an iterable containing (actual value, human readable name) tuples.
samfundet.RecruitmentAdmission.recruiter_status: (fields.E005) 'choices' must be an iterable containing (actual value, human readable name) tuples.
```
This PR fixes them
=> Fix recruitment choices error

backend/root/management/commands/seed_scripts/venues.py
Due to reservation being protected, need to delete it on venue seed
=> hotfix delete existing reservation on seed

frontend/src/Components/Button/Button.tsx
=> Add type="button" as default for Button component

frontend/src/Components/UserFeedback/UserFeedback.module.scss, frontend/src/Components/UserFeedback/UserFeedback.tsx
=> Div bug fix

frontend/src/Pages/RecruitmentPage/RecruitmentPage.tsx
Added check if logged in to recruitment page, and redirect if not logged in
=> add check of login to recruitmentpage

frontend/src/Pages/RecruitmentAdmissionFormPage/RecruitmentAdmissionFormPage.tsx
=> add redirect button when not logged in on recruitmentadmission

frontend/src/Pages/RecruitmentPage/RecruitmentPage.tsx
=> rename organization to my applications

frontend/src/Components/BackButton/BackButton.stories.tsx, frontend/src/Components/BackButton/BackButton.tsx, frontend/src/Components/BackButton/index.ts, frontend/src/Components/index.ts, frontend/src/PagesAdmin/AdminPageLayout/AdminPageLayout.tsx, frontend/src/PagesAdmin/InformationFormAdminPage/InformationFormAdminPage.module.scss, frontend/src/hooks.ts
Så at backbutton var i en annen fil, flyttet det til et eget komponent
=> add component for backbutton

frontend/src/context/AuthContext.tsx
It's very useful to know if our auth state is loading or not.
=> Add loading state to AuthContext

frontend/src/App.tsx
Sorry @tiniuspre 
Maybe we can enable it again for april fools or something
=> Disable CommandSprut

frontend/src/Pages/RecruitmentPage/RecruitmentPage.tsx
Seems like a merge gone wrong, but Recruitmentpage would display the old version of personalrow without checking login
=> remove duplicate of personal row in recruimentpage

backend/Pipfile
=> Add ruff:apply script to Pipfile

frontend/src/Pages/RecruitmentApplicationFormPage/RecruitmentApplicationFormPage.tsx, frontend/src/api.ts
somebody removed getRecruitmentAdmissionForApplicant and replaced it with another API during refactor  >:/
=> fix recruitment admission form fetched wrong api

frontend/src/PagesAdmin/RecruitmentRecruiterDashboardPage/RecruitmentRecruiterDashboardPage.tsx
Having navigate in useEffect deplist will cause infinite loops.
=> Fix Recruiter Dashboard infinite loop

frontend/src/PagesAdmin/RecruitmentAdminPage/RecruitmentAdminPage.tsx
=> fix view recruitment button

docker-compose.yml
Får lage et issue på å fikse dette da ig ...
=> remove cypress from docker compose

backend/root/management/commands/seed_scripts/__init__.py, backend/root/management/commands/seed_scripts/recruitment_position_interviewers.py
=> adds seed script for possible interviewers on position

frontend/src/PagesAdmin/RecruitmentApplicantAdminPage/RecruitmentApplicantAdminPage.tsx
Add a link so that admin users can view other applications of a user, from the admin view applicant page.
=> add link to other applications

.vscode/extensions.json, .vscode/settings.default.json
=> update extensions and suggested settings

frontend/src/Pages/ComponentPage/ComponentPage.tsx
Kinda annoying not being able to interact with any of the other elements on the page due to rekefisking. So this adds a simple button to show rekefisking
=> Disable rekefisking by default on component page

frontend/src/PagesAdmin/RecruitmentFormAdminPage/RecruitmentFormAdminPage.tsx, frontend/src/PagesAdmin/RecruitmentFormAdminPage/recruitmentSchema.ts, frontend/src/i18n/constants.ts, frontend/src/i18n/translations.ts
Other changes:
* Tweak regex to allow copy-pasting YouTube links
* Add description
=> Fix promo video message

frontend/src/Pages/ContributorsPage/ContributorItem.tsx, frontend/src/Pages/ContributorsPage/ContributorsPage.tsx, frontend/src/Pages/ContributorsPage/components/Contributor/index.ts, frontend/src/Pages/ContributorsPage/components/index.ts, frontend/src/Pages/ContributorsPage/types.ts
And clean up some formatting and file structure
=> Update contributors page

frontend/src/PagesAdmin/RecruitmentGangAllApplicantsAdminPage/RecruitmentGangAllApplicantsAdminPage.tsx, frontend/src/dto.ts
=> adds new column and implements type map

frontend/src/Components/NumberInput/NumberInput.tsx
Holding shift while using up/down arrow buttons, will increment/decrement by 10 instead of 1.
=> NumberInput: increment/decrement by 10 when holding shift and using arrow buttons

docs/editors/vim.md
=> Docs for configuring neovim for samf4

frontend/src/PagesAdmin/RecruitmentUnprocessedApplicantsPage/RecruitmentUnprocessedApplicantsPage.tsx
Removed back button on http://localhost:3000/control-panel/recruitment/2/unprocessed-applicants/ as the issue described.
=> Removed back button

frontend/src/router/router.tsx
Moved crumb under "parent crumb" and added crumb to the specific page.
URL: http://localhost:3000/control-panel/recruitment/2/recruitment-overview/
=> Moved route and added crumb

frontend/src/routes/frontend.ts
http://localhost:3000/control-panel/recruitment/2/users-without-interview/
=> Changed applications to interview

frontend/src/Pages/LycheReservationPage/Components/FindAvailableTablesForm/FindAvailableTablesForm.tsx, frontend/src/Pages/LycheReservationPage/Components/FindAvailableTablesForm/FindAvailableTablesSchema.ts, frontend/src/Pages/LycheReservationPage/Components/ReserveTableForm/ReserveTableForm.tsx, frontend/src/Pages/LycheReservationPage/Components/ReserveTableForm/ReserveTableSchema.ts, frontend/src/Pages/LycheReservationPage/LycheReservationPage.tsx, frontend/src/apis/sulten/sultenApis.ts, frontend/src/i18n/constants.ts, frontend/src/i18n/translations.ts, frontend/src/schema/reservation.ts, frontend/src/types/sultenTypes.ts
This PR makes a somewhat working reservation system. This is the second PR of a trilogy of PR-s. The following improvements should be made:
Permissions are weird. The view used should probably be a post-only view, because users should not be able to see a list of their reservations etc. 
We might want to implement email confirmations
Should lyche use a slug? It's currently just a random number (8) used to identified venue
I think there are other limitations, lmk if you find any
=> Make a working reservation system

frontend/src/Components/BuyButton/BuyButton.tsx, frontend/src/Pages/EventPage/EventPage.tsx, frontend/src/Pages/HomePage/components/EventCarousel/EventCarousel.tsx, frontend/src/apis/billig/billigDtos.ts, frontend/src/dto.ts, frontend/src/i18n/constants.ts, frontend/src/i18n/translations.ts
On event card: (*styling later*)
On event detail page:
=> Adds billig buy button to billig event detail page

backend/samfundet/serializers.py
=> Send user roles to frontend in user object

docs/technical/pipeline.md
=> update ruff documentation

docs/technical/backend/permissions.md
=> write some permission docs
